/**
 * Reports page
 */

import { DashboardLayout } from '../layouts/DashboardLayout';

interface Report {
  id: string;
  title: string;
  generatedBy: string;
  date: string;
  type: 'clinic' | 'consultation' | 'health-trends';
}

export const Reports = () => {
  const reports: Report[] = [
    {
      id: '1',
      title: 'Monthly Clinic Report',
      generatedBy: 'Dr. Admin',
      date: '2024-01-10',
      type: 'clinic',
    },
    {
      id: '2',
      title: 'Consultation Summary - John Doe',
      generatedBy: 'Dr. Smith',
      date: '2024-01-12',
      type: 'consultation',
    },
    {
      id: '3',
      title: 'Health Trends Analysis Q4 2024',
      generatedBy: 'Analytics Team',
      date: '2024-01-05',
      type: 'health-trends',
    },
  ];

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'clinic':
        return '🏥';
      case 'consultation':
        return '👨‍⚕️';
      case 'health-trends':
        return '📈';
      default:
        return '📄';
    }
  };

  return (
    <DashboardLayout>
      <div className="mx-auto w-full max-w-7xl p-4 sm:p-6 lg:p-8">
        <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h1 className="text-2xl font-bold text-slate-900 sm:text-3xl">Reports</h1>
            <p className="text-sm text-slate-500">Mobile-ready summaries and downloadable records</p>
          </div>
          <button className="inline-flex items-center justify-center rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-blue-700">
            + Generate Report
          </button>
        </div>

        {/* Reports List */}
        <div className="grid gap-4 lg:grid-cols-2">
          {reports.map((report) => (
            <div key={report.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:shadow-md sm:p-6">
              <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                <div className="flex items-start gap-4 min-w-0">
                  <span className="text-4xl shrink-0">{getTypeIcon(report.type)}</span>
                  <div>
                    <h3 className="wrap-break-word text-lg font-bold text-slate-900">{report.title}</h3>
                    <p className="wrap-break-word text-sm text-slate-500">
                      Generated by {report.generatedBy} on {report.date}
                    </p>
                  </div>
                </div>
                <button className="w-fit text-sm font-semibold text-blue-600 hover:text-blue-700">
                  Download
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </DashboardLayout>
  );
};
