/**
 * Reports page
 */

import { DashboardLayout } from '../layouts/DashboardLayout';

interface Report {
  id: string;
  title: string;
  generatedBy: string;
  date: string;
  type: 'clinic' | 'consultation' | 'health-trends';
}

export const Reports = () => {
  const reports: Report[] = [
    {
      id: '1',
      title: 'Monthly Clinic Report',
      generatedBy: 'Dr. Admin',
      date: '2024-01-10',
      type: 'clinic',
    },
    {
      id: '2',
      title: 'Consultation Summary - John Doe',
      generatedBy: 'Dr. Smith',
      date: '2024-01-12',
      type: 'consultation',
    },
    {
      id: '3',
      title: 'Health Trends Analysis Q4 2024',
      generatedBy: 'Analytics Team',
      date: '2024-01-05',
      type: 'health-trends',
    },
  ];

  const slugify = (value: string) =>
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '');

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'clinic':
        return '🏥';
      case 'consultation':
        return '👨‍⚕️';
      case 'health-trends':
        return '📈';
      default:
        return '📄';
    }
  };

  const getReportBody = (report: Report) => {
    switch (report.type) {
      case 'clinic':
        return [
          '# Monthly Clinic Report',
          '',
          `Generated by ${report.generatedBy} on ${report.date}`,
          '',
          '## Highlights',
          '- Clinic throughput remained stable across the month.',
          '- Follow-up appointments were prioritized for active patients.',
          '- No critical workflow blockers were reported in the review window.',
        ].join('\n');
      case 'consultation':
        return [
          '# Consultation Summary - John Doe',
          '',
          `Generated by ${report.generatedBy} on ${report.date}`,
          '',
          '## Visit Summary',
          '- Chief concern reviewed and documented during the consultation.',
          '- Care plan shared with the patient for follow-up and monitoring.',
          '- Recommend reviewing medications and scheduling the next visit as needed.',
        ].join('\n');
      case 'health-trends':
        return [
          '# Health Trends Analysis Q4 2024',
          '',
          `Generated by ${report.generatedBy} on ${report.date}`,
          '',
          '## Insights',
          '- Seasonal utilization trends were consistent with previous quarters.',
          '- Preventive care follow-up remained the strongest opportunity area.',
          '- Patient engagement improved when reports were shared early.',
        ].join('\n');
      default:
        return [
          `# ${report.title}`,
          '',
          `Generated by ${report.generatedBy} on ${report.date}`,
        ].join('\n');
    }
  };

  const handleDownload = (report: Report) => {
    const body = getReportBody(report);
    const blob = new Blob([body], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${slugify(report.title)}-${report.date}.md`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  };

  return (
    <DashboardLayout>
      <div className="mx-auto w-full max-w-7xl p-4 sm:p-6 lg:p-8">
        <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h1 className="text-2xl font-bold text-slate-900 sm:text-3xl">Reports</h1>
            <p className="text-sm text-slate-500">Mobile-ready summaries and downloadable records</p>
          </div>
          <button className="inline-flex items-center justify-center rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-blue-700">
            + Generate Report
          </button>
        </div>

        {/* Reports List */}
        <div className="grid gap-4 lg:grid-cols-2">
          {reports.map((report) => (
            <div key={report.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:shadow-md sm:p-6">
              <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                <div className="flex items-start gap-4 min-w-0">
                  <span className="text-4xl shrink-0">{getTypeIcon(report.type)}</span>
                  <div>
                    <h3 className="wrap-break-word text-lg font-bold text-slate-900">{report.title}</h3>
                    <p className="wrap-break-word text-sm text-slate-500">
                      Generated by {report.generatedBy} on {report.date}
                    </p>
                  </div>
                </div>
                <button
                  type="button"
                  onClick={() => handleDownload(report)}
                  className="w-fit text-sm font-semibold text-blue-600 hover:text-blue-700"
                >
                  Download
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </DashboardLayout>
  );
};
